// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		double r = Math.random();
		int numTests = Integer.parseInt(args[0]);
		int greaterThanHalf = 0;
		int lessOrEqualToHalf = 0;
		for (int i = 0; i < numTests; i++) {
			r = Math.random();
			if (r <= 0.5) {
				lessOrEqualToHalf++;
			} else {
				greaterThanHalf++;
			}
		}
		if (greaterThanHalf == 0 || lessOrEqualToHalf == 0) {
			System.out.println("> 0.5: " + greaterThanHalf);
			System.out.println("<= 0.5: " + lessOrEqualToHalf);
			System.out.println("Ratio: N/A");
		} else {
			double ratioG = (double) greaterThanHalf / lessOrEqualToHalf;
			double ratioL = (double) lessOrEqualToHalf / greaterThanHalf;
			System.out.println("> 0.5: " + greaterThanHalf);
			System.out.println("<= 0.5: " + lessOrEqualToHalf);
			if (greaterThanHalf > lessOrEqualToHalf) {
				System.out.println("Ratio: " + ratioL);

			} else {
				System.out.println("Ratio: " + ratioG);

			}
		}
	}
}
